#IconUnlock.draggable.vertical = true;

springBack = (view) ->
  view.animate
    properties:
      x: view.originalFrame.x
      y: view.originalFrame.y
    curve: springCurve
  toggleIconUnlock()
  return

toggleIconUnlock = ->
  if IconUnlockOn.opacity == 1
    IconUnlockOn.opacity = 0
    IconUnlockOff.opacity = 1
  else
    IconUnlockOn.opacity = 1
    IconUnlockOff.opacity = 0
  return

springCurve = 'spring(1000, 30, 2000)'
IconUnlockOn.opacity = 0
#IconUnlock.draggable.enabled = true;
IconUnlock.draggable.horizontal = true
# On a click, go to the next state
IconUnlock.on Events.Click, ->
IconUnlock.on Events.DragStart, ->
  IconUnlockOn.opacity = 1
  IconUnlockOff.opacity = 0
  return
IconUnlock.on Events.DragEnd, ->
  if IconUnlock.midY < 200
    # Dragged up
    IconUnlock.animateTo { y: -IconUnlock.height }, 200
    #popIcon(Heart)
  else if IconUnlock.midY > Phone.height - 200
    # Dragged down
    IconUnlock.animateTo { y: Phone.height + IconUnlock.height }, 200
    #popIcon(Cross)
  else
    # Not dragged enough, spring back
    springBack IconUnlock
  return

# ---
# generated by js2coffee 2.1.0